services:
  - type: web
    name: telegram-subscription-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
